
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/noelialopez.github.io' #change it according to your repository name



# Profile information
yourname: NOELIA LOPEZ  ## put your name
title: 'DATA SCIENTIST'  ## your title
location: SYDNEY , AUSTRALIA


## Social Profiles
facebook: https://www.facebook.com/noni.bolson  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: www.linkedin.com/in/noelia-carolina-lópez  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
