
title: My Resume
url: 'https://drive.google.com/file/d/1riozcgKYb3fl--IwROaT6hKOMotIqaCm/view?usp=sharing'
baseurl: '/noelialopez.github.io' #change it according to your repository name



# Profile information
yourname: Noelia Lopez  ## put your name
title: 'GRAPHIC &amp; DATA SCIENTIST'  ## your title
location: Sydney, NSW


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
